<h2>Kmom10</h2>
<p><a hreF="http://www.student.bth.se/~siso18/dbwebb-kurser/htmlphp/me/kmom10/bmo/home.php">http://www.student.bth.se/~siso18/dbwebb-kurser/htmlphp/me/kmom10/bmo/home.php</a></p>

<p>För Kmom10 har jag valt att göra en simpel, lättnavigerad hemsida med neutrala färger. En hemsida bör enligt mig alltid vara lättnavigerad, så det är något som jag sätter stort fokus på. Allting man kan tänka sig behöva komma åt presenteras i huvudmenyn eller sidmenyerna som används på vissa av sidorna. Anledningen till att jag valt neutrala färger är för att hemsidan handlar om ett museum för olika föremål kopplade till begravningar, vilket jag tycker man bör ha en respektfull framtoning kring. Jag valde att använda mig av Bootstrap för designen på denna sida.</P>

<p>På förstasidan presenteras man tydligt med hemsidans syfte samt vad man kan hitta på hemsidan. Det finns även i sidomenyn en länk till ett kontaktformulär, så att man lätt kommer åt den som driver sidan. Jag hittade egentligen ingen bra bild som kunde användas i presentationssyfte på förstasidan från de inkluderade filerna. Annars hade jag gärna haft en bild på själva museet eller dylikt.</p>

<p>Allt innehåll i databasen presenteras på ett attraktivt sätt i min tolkning av BMO. Objekten presenteras i rutnätslayout på sin sida med bilder i tumnagelsstorlek. Väl inne på sidan för ett enskilt objekt kan man läsa beskrivningen att objektet samt få tillgång till andra storlekar av tumnagelsbilden. På sidan för artiklar presenteras man istället för ett mer bloggliknande flöde där titel, författare, datum för publicering, beskrivning och en läs mer knapp. Klickar någonstans på en artikel så kommer man till en ensam sida för just den artikeln, där man kan läsa innehållet.</p>

<p>På om-sidan kan man läsa den fullständiga texten om vad BMO är och varför sidan finns. Man får även tillgång till samma kontaktformulär som på startsidan. Via om-sidan kan man läsa om utvecklaren av sidan, liknande beskrivningen från me-sidan.</p>

<p>Generellt tycker jag att projektet har varit kul och lärorikt att genomföra. På grund av en krissituation hos en nära anhörig hamnade jag efter en hel del i kursen och har kämpat för att komma ikapp samtidigt mycket annat pågått. Till slut känns det ändå som att jag fått ihop projektet och en sida som jag är hyfsat nöjd över. Tyvärr har jag inte kunna lägga så mycket tid på extra funktioner för sidan men jag fick helt enkelt fokusera på att få klart den så snart som möjligt. Rent längd och svårighetsmässigt tycker jag detta moment var perfekt, även om min erfarenhet av kursmomentet kantats av ganska mycket annat tråkigt omkring det.</p>

<p>Kursen i sin helhet har varit bra och väldigt nyttig repetition om grunderna i PHP och jag känner betydligt mer trygg i språket nu jämfört med hur det kändes innan. Jag skulle vilja föreslå att det görs lite tydligare koppling mellan de enskilda kursmomenten och tillhörande lektioner på YouTube. Jag har i regel sett alla sändningar i efterhand och då har det varit ganska svårt att hitta vilket avsnitt som innehåller den information som krävs för en viss uppgift i ett kursmoment. Jag skulle absolut rekommendera kursen till de som vill komma igång med webbprogrammering men som vill ha en “mjuk start”. För mig personligen får kursen en 7:a på en skala om 1-10.</p>
